import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { commerce } from "../lib/commerce";
import { IProduct } from "../models/Product";
import { Products } from "../components";

export async function getStaticProps() {
  const { data: products } = await commerce.products.list();
  const { data: cart } = await commerce.cart.retrieve();

  return {
    props: {
      products,
      cart,
    },
  };
}

type Props = {
  products: IProduct[];
};

const onAddToCart = () => {
  console.log("hello");
};

const Home: NextPage<Props> = ({ products }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next E-Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello World</h1>
        <div>
          <Products />
        </div>
      </main>
    </div>
  );
};

export default Home;
