import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Products } from "../components";
import commerce from "../lib/commerce";
import styles from "../styles/Home.module.css";
import { IProduct, GetProductsData } from "../types/types";

export const getStaticProps: GetStaticProps = async (context) => {
  const { data: products }: GetProductsData = await commerce.products.list();

  return {
    props: {
      products,
    },
  };
};

type Props = {
  products?: IProduct[];
};

const Home: NextPage<Props> = ({ products }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next E-Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {products?.map((product) => {
        return (
          <li key={product.id}>
            {product.name} {product.price.formatted_with_symbol}{" "}
          </li>
        );
      })}

      <main className={styles.main}>
        <div>
          <Products products={products} />
        </div>
      </main>
    </div>
  );
};

export default Home;
